baseURL = "/"
title = "Spectral"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Ben's Nurture Africa Trip" # title for frontpage, may include image
copyright = "Ben Clarke"
description = 'I am off to Uganda again and I need your help'
startbuttonText = "Donate to the Cause"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Why am I going again?'
body = '''
Well, I have 2 reasons. 1 being pretty selfish and 1 being genuine.  
1 - **I feel like I have something to offer in the technology space since my graduation and subsequent employment**  
2 - **I want to see how Nansana has improved since I was last there(This is the selfish reason)**  
  
Below are some of my favourite memories I have from my last time in Nansana in 2016  
'''

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Add an memorable image here'
body = 'Description of image here'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Add an memorable image here'
body = 'Description of image here'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Add an memorable image here'
body = 'Description of image here'

[params.three]
enable = true
title = 'So how can you help?'
body = '''
Well, I am fundraising in some different ways which are as follows:
'''

[[params.three.feature]]
icon = "fa-youtube"
title = "My Youtube Channel"
body = "I am documenting my fundraising and the trip itself on my youtube channel. Tuning in and spreading the word is incredibly valuable and hugely appreciated."

[[params.three.feature]]
icon = "fa-laptop"
title = "Supporters Section"
body = "You may have already seen it, but there is a supporters section above where I put the names of people who have donated and contributed to the trip."

[[params.three.feature]]
icon = "fa-shirt"
title = "Branded sweatshirts and t-shirts"
body = "I will be wearing sweatshirts and t-shirts with company logos on them as purchasable ad space. Individuals can also purchase space on these garments if desired."

[[params.three.feature]]
icon = "fa-heart"
title = "Your love and support"
body = "You can still support Nurture Africa and my trip by simply spreading the word. Re-sharing social media posts, chatting with friends and family about the work we do, sending me questions you may have. All of these things help."

[params.cta]
enable = true
title = "Donation Link ->"
body = "If you would like to do some independant research of Nurture Africa and the wonderful work they do ->"

[[params.cta.link]]
href = "#"
text = "Donate"
special = true

[[params.cta.link]]
href = "#"
text = "Nurture Africa Homepage"
special = false

[params.contact]
enable = true
title = "Get in touch with me."
body = "If you don't do social media and would like to contact me via email"
email = "ben.clarke14@gmail.com"
subject = "Nurture Africa Enquiry"
formspree_form_id = "xwkjkzkj"

[params.social]
twitter = "benjithedev"
facebook = "ben.clarke32"
instagram = "benjimanclarke96"
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"
